CREATE TABLE IF NOT EXISTS "Users" (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "Orders" (
    Id SERIAL PRIMARY KEY,
    Price DECIMAL(8,2) NOT NULL,
    Description VARCHAR(100) NOT NULL,
    Status VARCHAR(100) NOT NULL,
    UserId INT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE
);
